### DISCUSSION TITLE
Scripting automations for day/night setting

### DISCUSSION THREAD

**Discussion by Aturner4444** [fwestenberg/reolink_dev#288] [Q&A]
Hi

I am new to Home Assistant, its not a platform I've ever used before, but as I've recently installed a ReoLink CCTV system that needs configuring beyond what the interface allows for, I think I've found the solution. It's irrelevant to my question really but I have found that the auto black and white mode is not functional on one of my cameras due to it picking up a little bit of street lighting, it however isn't enough light to make for a good picture. So I'm trying to automate the blackandwhite mode to coincide with some sort of dusk till dawn timer.

```
- id: '1633015164930'
  alias: New Automation
  description: ''
  trigger:
  - platform: time
    at: '17:03'
  condition: []
  action:
  - service: reolink_dev.set_daynight
    data: {}
    target:
      entity_id:
      - camera.back_garden
  mode: BLACKANDWHITE
```

I have tried several different ways but cannot seem to figure it out, I realise there currently isn't a dusk till dawn timer there, I just wanted to figure out how to interact with the camera first.

Can someone please help?

Thank you!
