### ISSUE TITLE
Periodic State Change Triggers Without Actually Changing State

### ISSUE THREAD

**Issue by mathmaniac43** [fwestenberg/reolink_dev#102]
**Describe the bug**
I have 4 Reolink cameras connected to Home Assistant using your new Home Assistant built-in integration. I have made a new templated integration to notify me when their state changes (for example, when they become 'unavailable'). However, I frequently get notified when the state does not change, and it goes from 'idle' to 'idle'. This is not actually a state value change and therefore should not trigger.

**To Reproduce**
Use the following automation, with triggering camera entities and notification service (I am using an Android phone as the target) replaced as appropriate:
```yaml
alias: Notify - Camera State Change
description: ''
trigger:
  - platform: state
    entity_id: 'camera.front_door, camera.driveway, camera.shed, camera.backyard'
    for: '00:00:60'
condition: []
action:
  - data:
      title: '{{trigger.entity_id}} State Changed'
      message: >-
        To {{trigger.to_state.state}}. From {{trigger.from_state.state}}. Time
        {{now()}}.
      data:
        clickAction: /history
    service: notify.mobile_app_phone
mode: queued
max: 10
```

If the camera(s) are working normally ('idle'), just wait for 10 or 20 minutes and notifications should periodically show up on your phone that indicate that the state has changed from 'idle' to 'idle'.

**Expected behavior**
I expect this notification to only be fired when the current state of a monitored camera changes from one state to a completely different state (such as 'idle' to 'unavailable').

**Screenshots**
![image](https://user-images.githubusercontent.com/918497/102274905-9c497680-3ef2-11eb-9b56-78f3397cd47b.png)

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: **0.118.5**
 - Reolink camera model: **RLC-410-5MP (x4)**
 - Camera firmware number **v3.0.0.116_20103100**

**Additional context**
I tried a bit of searching to see if this was a general Home Assistant Core issue, but did not see anything. I am not sure where filtering state changes is supposed to occur (be it in the integrations or in Core itself).

If there is any assistance I can provide or more information that would be helpful, please let me know. Thanks!
