### ISSUE TITLE
Reolink does not display after upgrading to HA core 2021.3.1

### ISSUE THREAD

**Issue by Amishman** [fwestenberg/reolink_dev#164]
**Describe the bug**
I upgraded from HA core 2021.2.3 to 2021.3.1 and now there is no image in the picture glance card in lovelace. There is a message where the image should be that states "Preview of the Front Door camera." When looking in configuration > integrations, the Reolink integration shows the camera as being unavailable.

**To Reproduce**
I restored a snapshot and went back to HA core 2021.2.3 and the image was there. Everything was working properly. I upgraded back to HA core 2021.3.1 and the camera did not work again.

**Expected behavior**
There should be an image of what the camera sees in the picture glance card.

**Screenshots**

**Environment:**
HA is installed in VirtualBox on Windows 10

Please provide useful information about your environment, like:
 - Home Assistant version: 2021.3.1
 - Reolink camera model: RLC-420-5MP
 - Camera firmware number: v2.0.0.448_19061408

**Additional context**
I have 2 error messages in my logs.

 `Logger: homeassistant.config_entries
Source: helpers/network.py:124
First occurred: 3:39:00 PM (1 occurrences)
Last logged: 3:39:00 PM

Error setting up entry Front Door for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 72, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-EC71DB57BF22'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 208, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 84, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 124, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
`

and this one.
`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:39:15 PM (5 occurrences)
Last logged: 3:48:03 PM

[140340687682768] Received invalid command: camera/stream
[140340669782000] Received invalid command: camera/stream
[140340666917696] Received invalid command: camera/stream

`
![camera_info](https://user-images.githubusercontent.com/5334426/110173829-366fdb00-7dcd-11eb-82cf-7daac1c0cca6.PNG)
![camera_unavailable](https://user-images.githubusercontent.com/5334426/110173833-37087180-7dcd-11eb-930c-1dec584282d8.PNG)
![Error setting up entry](https://user-images.githubusercontent.com/5334426/110173834-37087180-7dcd-11eb-82e5-a13608c01b72.PNG)
![invalid command camera-stream](https://user-images.githubusercontent.com/5334426/110173835-37a10800-7dcd-11eb-90eb-905dd5f96405.PNG)

**Comment by Amishman** [comment]
I tried uninstalled/reinstalled but it did not work. After you install the repository in HACS and reboot, I get the following error message in the logs.

`Logger: homeassistant.loader
Source: loader.py:802
First occurred: 9:26:38 PM (1 occurrences)
Last logged: 9:26:38 PM

No 'version' key in the manifest file for custom integration 'reolink_dev'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'reolink_dev'`

Then when I install the Reolink integration and reboot, I get the same error message as above.

![image](https://user-images.githubusercontent.com/5334426/110192262-e445ae80-7dfa-11eb-93b0-a2a6058f55ab.png)

**Comment by xannor** [comment]
The underlying error is NoURLAvailableError which sounds like either the hostname/ip you are providing is incorrect or that your camera is not resolvable from Home Assistant. If you can get shell access to your HA install, can you ping the camera with the info you are providing the integration?

I ask because I have stepped from 2021.2.3 through to 2021.3.2 and my three cameras(511, 510, and 520) work fine in each one, but I have had problems in the past between versions with name resolution.

**Comment by bakoscsaba** [comment]
I have the same issue after upgrading from 2021.2.3 to 2021.3.2. After deleting the integration and installing again, no device and entities are created.

![image](https://user-images.githubusercontent.com/64539071/110222141-69e75e00-7ed0-11eb-9508-99bd4707f59e.png)

If I rollback to 2021.2.3 the integration works OK.

**Comment by xannor** [comment]
Can you do a terminal connection and ping the hostname/ip in both versions? The error reported is noURLAvailableError which means the URL that it is trying to connect to cannot resolve. This is usually a name resolution error, which, if you are using HASSOS or the containerized versions of HA, can change from version to version. 

An additional thing to try is to add debugging. If you add/change in your configuration.yaml:
```
logger:
  logs:
    custom_components.reolink_dev: debug
    reolink: debug
```

then in your working version note what hostname/ip it reports talking to and then in 2021.3.2 see what it attempts to talk to.

**Comment by Amishman** [comment]
I am able to ping the camera's IP (10.0.0.23) in both versions.

I set debug on both versions and restarted. I have attached both logs.
[home-assistant-core-2021.3.1.log](https://github.com/fwestenberg/reolink_dev/files/6096441/home-assistant-core-2021.3.1.log)

[home-assistant-core-2021.2.3.log](https://github.com/fwestenberg/reolink_dev/files/6096440/home-assistant-core-2021.2.3.log)

**Comment by xannor** [comment]
Ok, I dug into this further and I traced it to a particular point, but I cannot determine why it is failing, I also cannot reproduce this in my dev environment with the current 4.0dev or the 3.1 you are using. The failure is occurring in the get_url function provided by HA, and according to the dev docs, it means that the install cannot generate a url with the needed requirements (in this case, prefer_external is false).

I do see that the smartthings integration has a similar issue logged in the core github, with no resolution other than to roll back. I also found a issue/conversion about Google Nest having an issue when the site is behind a proxy, though this is for an older version, and the discussion was about the error message not the get_url method. 

As to what could have changed between 2.x and 3.x that would cause get_url to not be able to generate a url on your setup, is unfortunately, beyond what I have experience with. The only other thing I can think of is, do you have anything in your config that limits/removes the internal url?

**Comment by fwestenberg** [comment]
I just update to the latest core also, but my integration is still running fine. Please go to Settings->general->Internal url. What address is filled in?

**Comment by Amishman** [comment]
Thank you both for your help with this. There is nothing listed in Configuration->general->Internal url in both versions.

![image](https://user-images.githubusercontent.com/5334426/110246323-283cce80-7f35-11eb-8ec2-d2150af5d498.png)

There is nothing inside the my config that has to do with an internal url. Here is my config. 
````
homeassistant:
  packages: !include_dir_named packages
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  logs:
    custom_components.reolink_dev: debug
    reolink: debug
    
frontend:
  themes: !include_dir_merge_named themes
  
# DuckDNS
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml


switch:
  - platform: template
    switches:
      digital_f:
        friendly_name: "Digital F"
        value_template: "{{ is_state('switch.picture_frame', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.frame
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.frame
````

**Comment by xannor** [comment]
What happens if you disable the DuckDNS integration and comment out the http: section? I wonder if in 3.x it is forcing an external only url.

**Comment by Amishman** [comment]
Yes, commenting out the http section and turning off DuckDNS did allow the camera to work in 2021.3.1. How do I get them both to work at the same time?

**Comment by xannor** [comment]
Eureka! I figured it out, or at least the cause...

Re-reading the docs for get url I noticed this line for the "default" behavior:

> Get an internal URL set by the user, or if not available, try to detect one from the network interface (based on http settings).

and I saw that you had an http section, so I gen'd a cert and setup https and now I can reproduce the error, so I believe that in 3.0 they changed something that throws with this configuration. I don't know a fix for the http setup but a workaround would be to use a ssl/proxy addon so HA can be unencrypted on 8123 but provide SSL over another port, or at least externally to the host on 8123.

**Comment by xannor** [comment]
I found a couple of issues in core that could be related so I linked them, this way it may draw some attention to this issue and get it solved faster, but as of right now it looks like a HA bug and not anything that can be done on this end.

**Comment by cd29** [comment]
yeah this seems to be the same issue as mine under #47569.  
I do have an internal http url setup, as well as an external one in the config.

**Comment by pniewiadowski** [comment]
I have faced this issue as well, and @xannor actualy point me to direction to resolve it.
The HA team depcate base_url in http component, and if you are using duckdns.org you have to change your configuration slighty to someting likt that:

```
configuration.yaml
homeassistant:
  customize: !include customize.yaml
  internal_url: http://internal_address:8123
  external_url: https://duck_dns_alias.duckdns.org
```
