### ISSUE TITLE
Switch for Color / Auto

### ISSUE THREAD

**Issue by Scope666** [fwestenberg/reolink_dev#183]
I know you have the **reolink_dev.set_daynight** service available, how can you turn this into a SWITCH in Home Assistant?  Similar to the IR Lights switch that this integration automatically creates.

I'd love to be able to display the switch right on the camera view, like I'm doing now for the IR Lights.

Thanks in advance for your help!

**Comment by fwestenberg** [comment]
Just create a [template switch](https://www.home-assistant.io/integrations/switch.template/) and call the service you mentioned.
So to switch between color/b&w, something like this should work:

```
switch:
  - platform: template
    switches:
      daylight:
        value_template: "{{ is_state_attr('camera.front_door', 'daynight_state', 'COLOR') }}"
        turn_on:
          service: reolink_dev.set_daynight
          data: 
            entity_id: camera.front_door
            mode: COLOR
        turn_off:
          service: reolink_dev.set_daynight
          data: 
            entity_id: camera.front_door
            mode: BLACKANDWHITE
```
