### ISSUE TITLE
Camera stream freeze at 02:00 (2 a.m.) nearly every night.

### ISSUE THREAD

**Issue by kolossboss** [fwestenberg/reolink_dev#62]
Hi,
my realink camera stops/freezes at 02:00 (2a.m.) nearly every night. Nothing special happen at 02:00.
Only a google Drive backup is started.

```
- id: '1541223656718'
  alias: Snapshot Google Drive
  trigger:
  - at: 02:00:00
    platform: time
  condition: []
  action:
  - service: rest_command.google_backup
```

I got this error message in the log

`2020-08-23 02:00:26 ERROR (MainThread) [custom_components.reolink_dev.camera] Got exception while fetching the state: `

Looks like this:

![IMG_1092](https://user-images.githubusercontent.com/11015086/90974778-92100080-e52e-11ea-940a-e1fc78ee9845.jpg)

All other cams (not reolink) works fine. Only restart server fix this issue temporary. What can cause this? Please help.
