### ISSUE TITLE
IR lights switch not added with version 0.8

### ISSUE THREAD

**Issue by badabing2005** [fwestenberg/reolink_dev#91]
It looks like with version 0.8
The IR lights entity is not added.

The documentation says:

> Depending on the camera, the following switches are created

So I suppose somehow it thinks that my NVR does not support IR lights, which it does.
It is: RLN8-410-E
Firmware: v2.0.0.271_20092801

**Comment by fwestenberg** [comment]
Can it be, for switching the IR lights you need to use the service reolink_dev.set_daynight?

**Comment by badabing2005** [comment]
> 
> 
> Can it be, for switching the IR lights you need to use the service reolink_dev.set_daynight?

Indeed yes,
This switch package works
```
platform: template
switches:
  camera_frontdoor_ir_lights:
    #value_template: "{{ is_state_attr('camera.front_door', 'ir_lights_enabled', true) }}"
    turn_on:
      service: reolink_dev.set_daynight
      data:
        entity_id: camera.nvr
        mode: AUTO
    turn_off:
      service: reolink_dev.set_daynight
      data:
        entity_id: camera.nvr
        mode: COLOR
```
The only issue is without an attribute for the value, the startup state is nondeterministic.
Perhaps once you support NVR, you can have each Camera's ISP values as attributes, and the template can get the value from it.
