### ISSUE TITLE
Service PTZ and error on the integrations

### ISSUE THREAD

**Issue by MiAutomations** [fwestenberg/reolink_dev#96]
Hello, 

I just trie to use the service reolink_dev.ptz_control (that is the service available on my HA) instead of the reolink.ptz_control
in the reolink C1 Model

![reolink service dev](https://user-images.githubusercontent.com/47602733/102009602-63fa3a80-3d30-11eb-840d-17b3e3bf4921.jpg)

I try to substitute the command on the following code, in order to get the PTZ control over the  lovelace card but without success for  now ... as you can see in the picture bellow I'm facing a error:

![reolink ptz-1](https://user-images.githubusercontent.com/47602733/102009410-2648e200-3d2f-11eb-9560-98df3c08afed.jpg)
 

```
type: picture-elements
entity: camera.camera_9
camera_image: camera.camera_9
camera_view: live
elements:
  - type: icon
    icon: 'mdi:arrow-up'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 25px
      bottom: 50px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: UP
  - type: icon
    icon: 'mdi:arrow-down'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 25px
      bottom: 0px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: DOWN
  - type: icon
    icon: 'mdi:arrow-left'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 50px
      bottom: 25px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: LEFT
  - type: icon
    icon: 'mdi:arrow-right'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 0px
      bottom: 25px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: RIGHT
  - type: icon
    icon: 'mdi:arrow-top-left'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 50px
      bottom: 50px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: LEFTUP
  - type: icon
    icon: 'mdi:arrow-top-right'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 0px
      bottom: 50px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: RIGHTUP
  - type: icon
    icon: 'mdi:arrow-bottom-left'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 50px
      bottom: 0px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: LEFTDOWN
  - type: icon
    icon: 'mdi:arrow-bottom-right'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      right: 0px
      bottom: 0px
    tap_action:
      action: call-service
      service: reolink_dev.ptz_control
      service_data:
        entity_id: camera.camera_9
        movement: RIGHTDOWN
```

But I'm also facing a error on the HA related to the reolink integration and i don't now if is related or not with the service that I'm trying to use ... 

```
Logger: homeassistant.setup
Source: setup.py:138
First occurred: December 12, 2020, 10:09:42 PM (1 occurrences)
Last logged: December 12, 2020, 10:09:42 PM

Setup failed for reolink: No setup function defined.
```
![Screenshot_2020-12-12-22-19-57-979_io homeassistant companion android](https://user-images.githubusercontent.com/47602733/102009530-e7675c00-3d2f-11eb-8aaa-f569354185de.jpg)
![Screenshot_2020-12-12-22-19-52-100_io homeassistant companion android](https://user-images.githubusercontent.com/47602733/102009531-e7fff280-3d2f-11eb-96c7-720dc1f8b932.jpg)

Can anyone please let me know if are using the service with success?  Or the way to correct this if this is related to the error on the integration? 

Thank you and best regards
